INSERT INTO manufacturers (name, country) VALUES ('Lockheed Martin', 'USA');
INSERT INTO manufacturers (name, country) VALUES ('Boeing', 'USA');
INSERT INTO manufacturers (name, country) VALUES ('Northrop Grumman', 'USA');
INSERT INTO manufacturers (name, country) VALUES ('General Dynamics', 'USA');
INSERT INTO manufacturers (name, country) VALUES ('BAE Systems', 'UK');
INSERT INTO manufacturers (name, country) VALUES ('SAAB Group', 'SWE');
INSERT INTO manufacturers (name, country) VALUES ('Dassault Aviation', 'FRA');
INSERT INTO manufacturers (name, country) VALUES ('Shenyang Aircraft Corporation', 'CHN');
INSERT INTO manufacturers (name, country) VALUES ('Sukhoi', 'RUS');
INSERT INTO manufacturers (name, country) VALUES ('Mikoyan', 'RUS');

INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('F22', 'FR34K', 1 );
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('AC-130J', '5P00K', 1);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('SU-27', 'K0BRA',9);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Super Hornet','DNK82', 2);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Rafale', '4N63L', 7);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('JAS 39 Gripen', 'V1K1N',6);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('MIG-29', '80R15', 10);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Eurofighter Typhoon', 'F1GHT', 5);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('F-35 Lightning II', 'L1GHS', 1);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Chengdu J-20', 'DR4GN', 8);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('B-2 Spirit', 'STLTH', 3);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('HAL Tejas', 'T3JAS', 13);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('J-10', 'F1R3R', 14);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('F-15 Eagle', '1GEAG', 11);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Su-57', 'ST34TH', 9);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('F-16 Fighting Falcon', '1RNF16', 15);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Eurofighter Typhoon', 'F1GH2', 5);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('F-22', 'R3D44', 1);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('F-22', 'ST3LT', 1);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('AC-130J', 'M5N3O', 1);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('SU-27', 'P7R8S', 9);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Super Hornet', 'K9T0U', 2);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('Rafale', 'V0W1X', 7);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('JAS 39 Gripen', 'Y2Z3A', 6);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('MIG-29', 'B4C5D', 10);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('A-10 Thunderbolt', 'E6F7G', 1);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('B-2 Spirit', 'H8I9J', 2);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('KC-135 Stratotanker', 'K0L1M', 3);
INSERT INTO planes (model, tail_number, manufacturer_id) VALUES ('C-17 Globemaster', 'N2O3P', 4);